// Generated by scripts/update_masterdata.py. Do not edit by hand.

export const MASTER_DATA_SOURCE = {
    "region": "jp",
    "repository": "Sekai-World/sekai-master-db-diff",
    "commit": "db430d712d9418d11977d7fa2b188b0babd30071",
    "committedAt": "2026-10-02T06:30:14Z",
    "tables": [
        "mysekaiMaterials",
        "mysekaiItems",
        "mysekaiFixtures",
        "mysekaiFixturePlants",
        "mysekaiSiteHarvestFixtures",
        "materials"
    ]
};

export const ITEM_CATALOG = {
    "mysekai_material": {
        "1": {
            "name": "想いの木材",
            "icon": "item_wood_1.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "2": {
            "name": "おもたい木材",
            "icon": "item_wood_2.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "3": {
            "name": "かるい木材",
            "icon": "item_wood_3.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "4": {
            "name": "ベタベタの樹液",
            "icon": "item_wood_4.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "5": {
            "name": "夕桐",
            "icon": "item_wood_5.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "6": {
            "name": "想いの石ころ",
            "icon": "item_mineral_1.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "7": {
            "name": "銅",
            "icon": "item_mineral_2.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "8": {
            "name": "鉄",
            "icon": "item_mineral_3.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "9": {
            "name": "粘土",
            "icon": "item_mineral_4.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "10": {
            "name": "きれいなガラス",
            "icon": "item_mineral_5.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "11": {
            "name": "きらきらクォーツ",
            "icon": "item_mineral_6.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "12": {
            "name": "ダイヤモンド",
            "icon": "item_mineral_7.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_3"
        },
        "13": {
            "name": "ねじ",
            "icon": "item_junk_1.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "14": {
            "name": "釘",
            "icon": "item_junk_2.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "15": {
            "name": "プラスチック",
            "icon": "item_junk_3.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "16": {
            "name": "モーター",
            "icon": "item_junk_4.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "17": {
            "name": "電池",
            "icon": "item_junk_5.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "18": {
            "name": "ライト",
            "icon": "item_junk_6.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "19": {
            "name": "電子基板",
            "icon": "item_junk_7.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "20": {
            "name": "四葉のクローバー",
            "icon": "item_plant_1.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_3"
        },
        "21": {
            "name": "さらさらリネン",
            "icon": "item_plant_2.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "22": {
            "name": "ふわふわコットン",
            "icon": "item_plant_3.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "23": {
            "name": "花びら",
            "icon": "item_plant_4.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "24": {
            "name": "まっさらな音色",
            "icon": "item_tone_8.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_1"
        },
        "32": {
            "name": "あおぞらシーグラス",
            "icon": "item_junk_8.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "33": {
            "name": "月光石",
            "icon": "item_mineral_8.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "34": {
            "name": "流れ星のかけら",
            "icon": "item_junk_9.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "35": {
            "name": "スカイブルーメモリア",
            "icon": "item_memoria_1.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "36": {
            "name": "パッションイエローメモリア",
            "icon": "item_memoria_2.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "37": {
            "name": "ポピーレッドメモリア",
            "icon": "item_memoria_3.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "38": {
            "name": "イエローグリーンメモリア",
            "icon": "item_memoria_4.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "39": {
            "name": "アプリコットメモリア",
            "icon": "item_memoria_5.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "40": {
            "name": "ストリクトブルーメモリア",
            "icon": "item_memoria_6.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "41": {
            "name": "ラブリーピンクメモリア",
            "icon": "item_memoria_7.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "42": {
            "name": "オパールグリーンメモリア",
            "icon": "item_memoria_8.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "43": {
            "name": "スリーズメモリア",
            "icon": "item_memoria_9.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "44": {
            "name": "ターコイズブルーメモリア",
            "icon": "item_memoria_10.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "45": {
            "name": "ジョリーコーラルメモリア",
            "icon": "item_memoria_11.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "46": {
            "name": "ロイヤルブルーメモリア",
            "icon": "item_memoria_12.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "47": {
            "name": "サンフラワーメモリア",
            "icon": "item_memoria_13.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "48": {
            "name": "ポカポカピンクメモリア",
            "icon": "item_memoria_14.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "49": {
            "name": "スプリンググリーンメモリア",
            "icon": "item_memoria_15.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "50": {
            "name": "カンパヌラパープルメモリア",
            "icon": "item_memoria_16.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "51": {
            "name": "ファリダメモリア",
            "icon": "item_memoria_17.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "52": {
            "name": "ウィスタリアメモリア",
            "icon": "item_memoria_18.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "53": {
            "name": "キャメルメモリア",
            "icon": "item_memoria_19.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "54": {
            "name": "シッスルメモリア",
            "icon": "item_memoria_20.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "55": {
            "name": "ブルーグリーンメモリア",
            "icon": "item_memoria_21.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "56": {
            "name": "オレンジメモリア",
            "icon": "item_memoria_22.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "57": {
            "name": "イエローメモリア",
            "icon": "item_memoria_23.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "58": {
            "name": "ピンクメモリア",
            "icon": "item_memoria_24.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "59": {
            "name": "レッドメモリア",
            "icon": "item_memoria_25.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "60": {
            "name": "ブルーメモリア",
            "icon": "item_memoria_26.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "61": {
            "name": "雪の結晶",
            "icon": "item_junk_10.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "62": {
            "name": "最高のオノの刃",
            "icon": "item_junk_11.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "63": {
            "name": "最高のツルハシの先端",
            "icon": "item_junk_12.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "64": {
            "name": "雷光石",
            "icon": "item_mineral_9.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "65": {
            "name": "彩虹のビードロ",
            "icon": "item_mineral_10.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "66": {
            "name": "ふわもこわたぐも",
            "icon": "item_junk_13.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "67": {
            "name": "一歌のセレブレーションフラワー",
            "icon": "item_birthday_flower_1.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "68": {
            "name": "咲希のセレブレーションフラワー",
            "icon": "item_birthday_flower_2.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "69": {
            "name": "穂波のセレブレーションフラワー",
            "icon": "item_birthday_flower_3.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "70": {
            "name": "志歩のセレブレーションフラワー",
            "icon": "item_birthday_flower_4.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "71": {
            "name": "みのりのセレブレーションフラワー",
            "icon": "item_birthday_flower_5.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "72": {
            "name": "遥のセレブレーションフラワー",
            "icon": "item_birthday_flower_6.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "73": {
            "name": "愛莉のセレブレーションフラワー",
            "icon": "item_birthday_flower_7.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "74": {
            "name": "雫のセレブレーションフラワー",
            "icon": "item_birthday_flower_8.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "75": {
            "name": "こはねのセレブレーションフラワー",
            "icon": "item_birthday_flower_9.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "76": {
            "name": "杏のセレブレーションフラワー",
            "icon": "item_birthday_flower_10.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "77": {
            "name": "彰人のセレブレーションフラワー",
            "icon": "item_birthday_flower_11.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "78": {
            "name": "冬弥のセレブレーションフラワー",
            "icon": "item_birthday_flower_12.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "79": {
            "name": "司のセレブレーションフラワー",
            "icon": "item_birthday_flower_13.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "80": {
            "name": "えむのセレブレーションフラワー",
            "icon": "item_birthday_flower_14.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "81": {
            "name": "寧々のセレブレーションフラワー",
            "icon": "item_birthday_flower_15.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "82": {
            "name": "類のセレブレーションフラワー",
            "icon": "item_birthday_flower_16.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "83": {
            "name": "奏のセレブレーションフラワー",
            "icon": "item_birthday_flower_17.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "84": {
            "name": "まふゆのセレブレーションフラワー",
            "icon": "item_birthday_flower_18.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "85": {
            "name": "絵名のセレブレーションフラワー",
            "icon": "item_birthday_flower_19.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "86": {
            "name": "瑞希のセレブレーションフラワー",
            "icon": "item_birthday_flower_20.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "87": {
            "name": "ミクのセレブレーションフラワー",
            "icon": "item_birthday_flower_21.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "88": {
            "name": "リンのセレブレーションフラワー",
            "icon": "item_birthday_flower_22.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "89": {
            "name": "レンのセレブレーションフラワー",
            "icon": "item_birthday_flower_23.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "90": {
            "name": "ルカのセレブレーションフラワー",
            "icon": "item_birthday_flower_24.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "91": {
            "name": "MEIKOのセレブレーションフラワー",
            "icon": "item_birthday_flower_25.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "92": {
            "name": "KAITOのセレブレーションフラワー",
            "icon": "item_birthday_flower_26.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "93": {
            "name": "セカイビッツ",
            "icon": "item_junk_14.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "94": {
            "name": "スペースコンポーネント",
            "icon": "item_junk_15.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "95": {
            "name": "シャボンバブル",
            "icon": "item_junk_16.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "96": {
            "name": "みずたま真珠",
            "icon": "item_junk_17.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "103": {
            "name": "遥のセレブレーションフラワー '26",
            "icon": "item_birthday_flower_6.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_2"
        },
        "124": {
            "name": "Leo/needのメモリア",
            "icon": "item_memoria_27.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "125": {
            "name": "MORE MORE JUMP！のメモリア",
            "icon": "item_memoria_28.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "126": {
            "name": "Vivid BAD SQUADのメモリア",
            "icon": "item_memoria_29.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "127": {
            "name": "ワンダーランズ×ショウタイムのメモリア",
            "icon": "item_memoria_30.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "128": {
            "name": "25時、ナイトコードで。のメモリア",
            "icon": "item_memoria_31.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        },
        "129": {
            "name": "バーチャル・シンガーのメモリア",
            "icon": "item_memoria_32.png",
            "folder": "mysekai/thumbnail/material",
            "rarity": "rarity_4"
        }
    },
    "mysekai_item": {
        "1": {
            "name": "白紙の設計図",
            "icon": "item_blank_blueprint.png",
            "folder": "mysekai/thumbnail/item"
        },
        "2": {
            "name": "余った設計図",
            "icon": "item_surplus_blueprint.png",
            "folder": "mysekai/thumbnail/item"
        },
        "5": {
            "name": "余ったレコード",
            "icon": "item_surplus_music_record.png",
            "folder": "mysekai/thumbnail/item"
        },
        "6": {
            "name": "フォトフィルム",
            "icon": "item_photofilm.png",
            "folder": "mysekai/thumbnail/item"
        },
        "7": {
            "name": "設計図のきれはし",
            "icon": "item_blueprint_fragment.png",
            "folder": "mysekai/thumbnail/item"
        }
    },
    "mysekai_fixture": {
        "118": {
            "name": "広葉樹の苗",
            "icon": "mdl_non1001_before_sapling1_118.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sapling1_118_1.png"
        },
        "119": {
            "name": "針葉樹の苗",
            "icon": "mdl_non1001_before_sapling1_119.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sapling1_119_1.png"
        },
        "120": {
            "name": "熱帯樹の苗",
            "icon": "mdl_non1001_before_sapling1_120.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sapling1_120_1.png"
        },
        "121": {
            "name": "夕桐の苗",
            "icon": "mdl_non1001_before_sapling1_121.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sapling1_121_1.png"
        },
        "126": {
            "name": "チューリップの球根/赤",
            "icon": "mdl_non1001_before_sprout1_126.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_126_1.png"
        },
        "127": {
            "name": "パンジーの種/赤系",
            "icon": "mdl_non1001_before_sprout1_127.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_127_1.png"
        },
        "128": {
            "name": "あじさいの種/紫",
            "icon": "mdl_non1001_before_sprout1_128.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_128_1.png"
        },
        "129": {
            "name": "スズランの種/白",
            "icon": "mdl_non1001_before_sprout1_129.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_129_1.png"
        },
        "130": {
            "name": "バラの種/赤",
            "icon": "mdl_non1001_before_sprout1_130.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_130_1.png"
        },
        "474": {
            "name": "チューリップの球根/ピンク",
            "icon": "mdl_non1001_before_sprout1_474.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_474_1.png"
        },
        "475": {
            "name": "パンジーの種/オレンジ系",
            "icon": "mdl_non1001_before_sprout1_475.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_475_1.png"
        },
        "476": {
            "name": "あじさいの種/水色",
            "icon": "mdl_non1001_before_sprout1_476.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_476_1.png"
        },
        "477": {
            "name": "スズランの種/ピンク",
            "icon": "mdl_non1001_before_sprout1_477.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_477_1.png"
        },
        "478": {
            "name": "バラの種/黄",
            "icon": "mdl_non1001_before_sprout1_478.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_478_1.png"
        },
        "479": {
            "name": "チューリップの球根/黄",
            "icon": "mdl_non1001_before_sprout1_479.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_479_1.png"
        },
        "480": {
            "name": "パンジーの種/紫系",
            "icon": "mdl_non1001_before_sprout1_480.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_480_1.png"
        },
        "481": {
            "name": "あじさいの種/ピンク",
            "icon": "mdl_non1001_before_sprout1_481.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_481_1.png"
        },
        "482": {
            "name": "スズランの種/水色",
            "icon": "mdl_non1001_before_sprout1_482.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_482_1.png"
        },
        "483": {
            "name": "バラの種/青",
            "icon": "mdl_non1001_before_sprout1_483.png",
            "folder": "mysekai/thumbnail/fixture",
            "remoteIcon": "mdl_non1001_before_sprout1_483_1.png"
        }
    },
    "material": {
        "1": {
            "name": "キュートピース",
            "icon": "material1.png",
            "folder": "thumbnail/material"
        },
        "2": {
            "name": "クールピース",
            "icon": "material2.png",
            "folder": "thumbnail/material"
        },
        "3": {
            "name": "ピュアピース",
            "icon": "material3.png",
            "folder": "thumbnail/material"
        },
        "4": {
            "name": "ハッピーピース",
            "icon": "material4.png",
            "folder": "thumbnail/material"
        },
        "5": {
            "name": "ミステリアスピース",
            "icon": "material5.png",
            "folder": "thumbnail/material"
        },
        "6": {
            "name": "キュートジェム",
            "icon": "material6.png",
            "folder": "thumbnail/material"
        },
        "7": {
            "name": "クールジェム",
            "icon": "material7.png",
            "folder": "thumbnail/material"
        },
        "8": {
            "name": "ピュアジェム",
            "icon": "material8.png",
            "folder": "thumbnail/material"
        },
        "9": {
            "name": "ハッピージェム",
            "icon": "material9.png",
            "folder": "thumbnail/material"
        },
        "10": {
            "name": "ミステリアスジェム",
            "icon": "material10.png",
            "folder": "thumbnail/material"
        },
        "11": {
            "name": "魔法の布",
            "icon": "material11.png",
            "folder": "thumbnail/material"
        },
        "12": {
            "name": "魔法の糸",
            "icon": "material12.png",
            "folder": "thumbnail/material"
        },
        "13": {
            "name": "ミュージックカード",
            "icon": "material13.png",
            "folder": "thumbnail/material"
        },
        "14": {
            "name": "ミラクルジェム",
            "icon": "material14.png",
            "folder": "thumbnail/material"
        },
        "15": {
            "name": "想いのカケラ",
            "icon": "material15.png",
            "folder": "thumbnail/material"
        },
        "16": {
            "name": "想いの純結晶",
            "icon": "material16.png",
            "folder": "thumbnail/material"
        },
        "17": {
            "name": "ふしぎな種",
            "icon": "material17.png",
            "folder": "thumbnail/material"
        },
        "18": {
            "name": "一歌のボーカルカード",
            "icon": "material18.png",
            "folder": "thumbnail/material"
        },
        "19": {
            "name": "咲希のボーカルカード",
            "icon": "material19.png",
            "folder": "thumbnail/material"
        },
        "20": {
            "name": "穂波のボーカルカード",
            "icon": "material20.png",
            "folder": "thumbnail/material"
        },
        "21": {
            "name": "志歩のボーカルカード",
            "icon": "material21.png",
            "folder": "thumbnail/material"
        },
        "22": {
            "name": "みのりのボーカルカード",
            "icon": "material22.png",
            "folder": "thumbnail/material"
        },
        "23": {
            "name": "遥のボーカルカード",
            "icon": "material23.png",
            "folder": "thumbnail/material"
        },
        "24": {
            "name": "愛莉のボーカルカード",
            "icon": "material24.png",
            "folder": "thumbnail/material"
        },
        "25": {
            "name": "雫のボーカルカード",
            "icon": "material25.png",
            "folder": "thumbnail/material"
        },
        "26": {
            "name": "こはねのボーカルカード",
            "icon": "material26.png",
            "folder": "thumbnail/material"
        },
        "27": {
            "name": "杏のボーカルカード",
            "icon": "material27.png",
            "folder": "thumbnail/material"
        },
        "28": {
            "name": "彰人のボーカルカード",
            "icon": "material28.png",
            "folder": "thumbnail/material"
        },
        "29": {
            "name": "冬弥のボーカルカード",
            "icon": "material29.png",
            "folder": "thumbnail/material"
        },
        "30": {
            "name": "司のボーカルカード",
            "icon": "material30.png",
            "folder": "thumbnail/material"
        },
        "31": {
            "name": "えむのボーカルカード",
            "icon": "material31.png",
            "folder": "thumbnail/material"
        },
        "32": {
            "name": "寧々のボーカルカード",
            "icon": "material32.png",
            "folder": "thumbnail/material"
        },
        "33": {
            "name": "類のボーカルカード",
            "icon": "material33.png",
            "folder": "thumbnail/material"
        },
        "34": {
            "name": "奏のボーカルカード",
            "icon": "material34.png",
            "folder": "thumbnail/material"
        },
        "35": {
            "name": "まふゆのボーカルカード",
            "icon": "material35.png",
            "folder": "thumbnail/material"
        },
        "36": {
            "name": "絵名のボーカルカード",
            "icon": "material36.png",
            "folder": "thumbnail/material"
        },
        "37": {
            "name": "瑞希のボーカルカード",
            "icon": "material37.png",
            "folder": "thumbnail/material"
        },
        "38": {
            "name": "ミクのボーカルカード",
            "icon": "material38.png",
            "folder": "thumbnail/material"
        },
        "39": {
            "name": "リンのボーカルカード",
            "icon": "material39.png",
            "folder": "thumbnail/material"
        },
        "40": {
            "name": "レンのボーカルカード",
            "icon": "material40.png",
            "folder": "thumbnail/material"
        },
        "41": {
            "name": "ルカのボーカルカード",
            "icon": "material41.png",
            "folder": "thumbnail/material"
        },
        "42": {
            "name": "MEIKOのボーカルカード",
            "icon": "material42.png",
            "folder": "thumbnail/material"
        },
        "43": {
            "name": "KAITOのボーカルカード",
            "icon": "material43.png",
            "folder": "thumbnail/material"
        },
        "44": {
            "name": "スタンプ交換券",
            "icon": "material44.png",
            "folder": "thumbnail/material"
        },
        "45": {
            "name": "★3メンバーセレクトチケット",
            "icon": "material45.png",
            "folder": "thumbnail/material"
        },
        "46": {
            "name": "★4メンバーセレクトチケット",
            "icon": "material46.png",
            "folder": "thumbnail/material"
        },
        "47": {
            "name": "ガチャシール券",
            "icon": "material47.png",
            "folder": "thumbnail/material"
        },
        "48": {
            "name": "限定ガチャシール券",
            "icon": "material48.png",
            "folder": "thumbnail/material"
        },
        "49": {
            "name": "ボーカルカード交換チケット",
            "icon": "material49.png",
            "folder": "thumbnail/material"
        },
        "50": {
            "name": "Leo/need\nボーカルカード交換チケット",
            "icon": "material50.png",
            "folder": "thumbnail/material"
        },
        "51": {
            "name": "MORE MORE JUMP！\nボーカルカード交換チケット",
            "icon": "material51.png",
            "folder": "thumbnail/material"
        },
        "52": {
            "name": "Vivid BAD SQUAD\nボーカルカード交換チケット",
            "icon": "material52.png",
            "folder": "thumbnail/material"
        },
        "53": {
            "name": "ワンダーランズ×ショウタイム\nボーカルカード交換チケット",
            "icon": "material53.png",
            "folder": "thumbnail/material"
        },
        "54": {
            "name": "25時、ナイトコードで。\nボーカルカード交換チケット",
            "icon": "material54.png",
            "folder": "thumbnail/material"
        },
        "55": {
            "name": "初心者限定セレクトチケット",
            "icon": "material55.png",
            "folder": "thumbnail/material"
        },
        "56": {
            "name": "[新春2022]★3メンバーセレクトチケット",
            "icon": "material56.png",
            "folder": "thumbnail/material"
        },
        "57": {
            "name": "願いの雫",
            "icon": "material57.png",
            "folder": "thumbnail/material"
        },
        "58": {
            "name": "★4メンバーセレクトチケット",
            "icon": "material58.png",
            "folder": "thumbnail/material"
        },
        "59": {
            "name": "★4メンバーセレクトチケット",
            "icon": "material59.png",
            "folder": "thumbnail/material"
        },
        "60": {
            "name": "一歌の想いの小瓶",
            "icon": "material60.png",
            "folder": "thumbnail/material"
        },
        "61": {
            "name": "咲希の想いの小瓶",
            "icon": "material61.png",
            "folder": "thumbnail/material"
        },
        "62": {
            "name": "穂波の想いの小瓶",
            "icon": "material62.png",
            "folder": "thumbnail/material"
        },
        "63": {
            "name": "志歩の想いの小瓶",
            "icon": "material63.png",
            "folder": "thumbnail/material"
        },
        "64": {
            "name": "みのりの想いの小瓶",
            "icon": "material64.png",
            "folder": "thumbnail/material"
        },
        "65": {
            "name": "遥の想いの小瓶",
            "icon": "material65.png",
            "folder": "thumbnail/material"
        },
        "66": {
            "name": "愛莉の想いの小瓶",
            "icon": "material66.png",
            "folder": "thumbnail/material"
        },
        "67": {
            "name": "雫の想いの小瓶",
            "icon": "material67.png",
            "folder": "thumbnail/material"
        },
        "68": {
            "name": "こはねの想いの小瓶",
            "icon": "material68.png",
            "folder": "thumbnail/material"
        },
        "69": {
            "name": "杏の想いの小瓶",
            "icon": "material69.png",
            "folder": "thumbnail/material"
        },
        "70": {
            "name": "彰人の想いの小瓶",
            "icon": "material70.png",
            "folder": "thumbnail/material"
        },
        "71": {
            "name": "冬弥の想いの小瓶",
            "icon": "material71.png",
            "folder": "thumbnail/material"
        },
        "72": {
            "name": "司の想いの小瓶",
            "icon": "material72.png",
            "folder": "thumbnail/material"
        },
        "73": {
            "name": "えむの想いの小瓶",
            "icon": "material73.png",
            "folder": "thumbnail/material"
        },
        "74": {
            "name": "寧々の想いの小瓶",
            "icon": "material74.png",
            "folder": "thumbnail/material"
        },
        "75": {
            "name": "類の想いの小瓶",
            "icon": "material75.png",
            "folder": "thumbnail/material"
        },
        "76": {
            "name": "奏の想いの小瓶",
            "icon": "material76.png",
            "folder": "thumbnail/material"
        },
        "77": {
            "name": "まふゆの想いの小瓶",
            "icon": "material77.png",
            "folder": "thumbnail/material"
        },
        "78": {
            "name": "絵名の想いの小瓶",
            "icon": "material78.png",
            "folder": "thumbnail/material"
        },
        "79": {
            "name": "瑞希の想いの小瓶",
            "icon": "material79.png",
            "folder": "thumbnail/material"
        },
        "80": {
            "name": "ミクの想いの小瓶",
            "icon": "material80.png",
            "folder": "thumbnail/material"
        },
        "81": {
            "name": "リンの想いの小瓶",
            "icon": "material81.png",
            "folder": "thumbnail/material"
        },
        "82": {
            "name": "レンの想いの小瓶",
            "icon": "material82.png",
            "folder": "thumbnail/material"
        },
        "83": {
            "name": "ルカの想いの小瓶",
            "icon": "material83.png",
            "folder": "thumbnail/material"
        },
        "84": {
            "name": "MEIKOの想いの小瓶",
            "icon": "material84.png",
            "folder": "thumbnail/material"
        },
        "85": {
            "name": "KAITOの想いの小瓶",
            "icon": "material85.png",
            "folder": "thumbnail/material"
        },
        "86": {
            "name": "サイドストーリーチケット",
            "icon": "material86.png",
            "folder": "thumbnail/material"
        },
        "87": {
            "name": "3900'sチケット",
            "icon": "material87.png",
            "folder": "thumbnail/material"
        },
        "88": {
            "name": "「コネクトライブ RESONANCE BEATS!!」コネクトライブver. ボーカル引き換えカード",
            "icon": "material88.png",
            "folder": "thumbnail/material"
        },
        "89": {
            "name": "白色の花びら",
            "icon": "material89.png",
            "folder": "thumbnail/material"
        },
        "90": {
            "name": "青色の花びら",
            "icon": "material90.png",
            "folder": "thumbnail/material"
        },
        "91": {
            "name": "緑色の花びら",
            "icon": "material91.png",
            "folder": "thumbnail/material"
        },
        "92": {
            "name": "赤色の花びら",
            "icon": "material92.png",
            "folder": "thumbnail/material"
        },
        "93": {
            "name": "橙色の花びら",
            "icon": "material93.png",
            "folder": "thumbnail/material"
        },
        "94": {
            "name": "紫色の花びら",
            "icon": "material94.png",
            "folder": "thumbnail/material"
        },
        "95": {
            "name": "ホワイトフォーチュンフラワー",
            "icon": "material95.png",
            "folder": "thumbnail/material"
        },
        "96": {
            "name": "ブルーフォーチュンフラワー",
            "icon": "material96.png",
            "folder": "thumbnail/material"
        },
        "97": {
            "name": "グリーンフォーチュンフラワー",
            "icon": "material97.png",
            "folder": "thumbnail/material"
        },
        "98": {
            "name": "レッドフォーチュンフラワー",
            "icon": "material98.png",
            "folder": "thumbnail/material"
        },
        "99": {
            "name": "オレンジフォーチュンフラワー",
            "icon": "material99.png",
            "folder": "thumbnail/material"
        },
        "100": {
            "name": "パープルフォーチュンフラワー",
            "icon": "material100.png",
            "folder": "thumbnail/material"
        },
        "101": {
            "name": "一歌の想いのカケラ",
            "icon": "material101.png",
            "folder": "thumbnail/material"
        },
        "102": {
            "name": "咲希の想いのカケラ",
            "icon": "material102.png",
            "folder": "thumbnail/material"
        },
        "103": {
            "name": "穂波の想いのカケラ",
            "icon": "material103.png",
            "folder": "thumbnail/material"
        },
        "104": {
            "name": "志歩の想いのカケラ",
            "icon": "material104.png",
            "folder": "thumbnail/material"
        },
        "105": {
            "name": "みのりの想いのカケラ",
            "icon": "material105.png",
            "folder": "thumbnail/material"
        },
        "106": {
            "name": "遥の想いのカケラ",
            "icon": "material106.png",
            "folder": "thumbnail/material"
        },
        "107": {
            "name": "愛莉の想いのカケラ",
            "icon": "material107.png",
            "folder": "thumbnail/material"
        },
        "108": {
            "name": "雫の想いのカケラ",
            "icon": "material108.png",
            "folder": "thumbnail/material"
        },
        "109": {
            "name": "こはねの想いのカケラ",
            "icon": "material109.png",
            "folder": "thumbnail/material"
        },
        "110": {
            "name": "杏の想いのカケラ",
            "icon": "material110.png",
            "folder": "thumbnail/material"
        },
        "111": {
            "name": "彰人の想いのカケラ",
            "icon": "material111.png",
            "folder": "thumbnail/material"
        },
        "112": {
            "name": "冬弥の想いのカケラ",
            "icon": "material112.png",
            "folder": "thumbnail/material"
        },
        "113": {
            "name": "司の想いのカケラ",
            "icon": "material113.png",
            "folder": "thumbnail/material"
        },
        "114": {
            "name": "えむの想いのカケラ",
            "icon": "material114.png",
            "folder": "thumbnail/material"
        },
        "115": {
            "name": "寧々の想いのカケラ",
            "icon": "material115.png",
            "folder": "thumbnail/material"
        },
        "116": {
            "name": "類の想いのカケラ",
            "icon": "material116.png",
            "folder": "thumbnail/material"
        },
        "117": {
            "name": "奏の想いのカケラ",
            "icon": "material117.png",
            "folder": "thumbnail/material"
        },
        "118": {
            "name": "まふゆの想いのカケラ",
            "icon": "material118.png",
            "folder": "thumbnail/material"
        },
        "119": {
            "name": "絵名の想いのカケラ",
            "icon": "material119.png",
            "folder": "thumbnail/material"
        },
        "120": {
            "name": "瑞希の想いのカケラ",
            "icon": "material120.png",
            "folder": "thumbnail/material"
        },
        "121": {
            "name": "ミクの想いのカケラ",
            "icon": "material121.png",
            "folder": "thumbnail/material"
        },
        "122": {
            "name": "リンの想いのカケラ",
            "icon": "material122.png",
            "folder": "thumbnail/material"
        },
        "123": {
            "name": "レンの想いのカケラ",
            "icon": "material123.png",
            "folder": "thumbnail/material"
        },
        "124": {
            "name": "ルカの想いのカケラ",
            "icon": "material124.png",
            "folder": "thumbnail/material"
        },
        "125": {
            "name": "MEIKOの想いのカケラ",
            "icon": "material125.png",
            "folder": "thumbnail/material"
        },
        "126": {
            "name": "KAITOの想いのカケラ",
            "icon": "material126.png",
            "folder": "thumbnail/material"
        },
        "127": {
            "name": "Leo/needの想いのカケラ",
            "icon": "material127.png",
            "folder": "thumbnail/material"
        },
        "128": {
            "name": "MORE MORE JUMP！の想いのカケラ",
            "icon": "material128.png",
            "folder": "thumbnail/material"
        },
        "129": {
            "name": "Vivid BAD SQUADの想いのカケラ",
            "icon": "material129.png",
            "folder": "thumbnail/material"
        },
        "130": {
            "name": "ワンダーランズ×ショウタイムの想いのカケラ",
            "icon": "material130.png",
            "folder": "thumbnail/material"
        },
        "131": {
            "name": "25時、ナイトコードで。の想いのカケラ",
            "icon": "material131.png",
            "folder": "thumbnail/material"
        },
        "132": {
            "name": "バーチャル・シンガーの想いのカケラ",
            "icon": "material132.png",
            "folder": "thumbnail/material"
        },
        "133": {
            "name": "一歌の想いの純結晶",
            "icon": "material133.png",
            "folder": "thumbnail/material"
        },
        "134": {
            "name": "咲希の想いの純結晶",
            "icon": "material134.png",
            "folder": "thumbnail/material"
        },
        "135": {
            "name": "穂波の想いの純結晶",
            "icon": "material135.png",
            "folder": "thumbnail/material"
        },
        "136": {
            "name": "志歩の想いの純結晶",
            "icon": "material136.png",
            "folder": "thumbnail/material"
        },
        "137": {
            "name": "みのりの想いの純結晶",
            "icon": "material137.png",
            "folder": "thumbnail/material"
        },
        "138": {
            "name": "遥の想いの純結晶",
            "icon": "material138.png",
            "folder": "thumbnail/material"
        },
        "139": {
            "name": "愛莉の想いの純結晶",
            "icon": "material139.png",
            "folder": "thumbnail/material"
        },
        "140": {
            "name": "雫の想いの純結晶",
            "icon": "material140.png",
            "folder": "thumbnail/material"
        },
        "141": {
            "name": "こはねの想いの純結晶",
            "icon": "material141.png",
            "folder": "thumbnail/material"
        },
        "142": {
            "name": "杏の想いの純結晶",
            "icon": "material142.png",
            "folder": "thumbnail/material"
        },
        "143": {
            "name": "彰人の想いの純結晶",
            "icon": "material143.png",
            "folder": "thumbnail/material"
        },
        "144": {
            "name": "冬弥の想いの純結晶",
            "icon": "material144.png",
            "folder": "thumbnail/material"
        },
        "145": {
            "name": "司の想いの純結晶",
            "icon": "material145.png",
            "folder": "thumbnail/material"
        },
        "146": {
            "name": "えむの想いの純結晶",
            "icon": "material146.png",
            "folder": "thumbnail/material"
        },
        "147": {
            "name": "寧々の想いの純結晶",
            "icon": "material147.png",
            "folder": "thumbnail/material"
        },
        "148": {
            "name": "類の想いの純結晶",
            "icon": "material148.png",
            "folder": "thumbnail/material"
        },
        "149": {
            "name": "奏の想いの純結晶",
            "icon": "material149.png",
            "folder": "thumbnail/material"
        },
        "150": {
            "name": "まふゆの想いの純結晶",
            "icon": "material150.png",
            "folder": "thumbnail/material"
        },
        "151": {
            "name": "絵名の想いの純結晶",
            "icon": "material151.png",
            "folder": "thumbnail/material"
        },
        "152": {
            "name": "瑞希の想いの純結晶",
            "icon": "material152.png",
            "folder": "thumbnail/material"
        },
        "153": {
            "name": "ミクの想いの純結晶",
            "icon": "material153.png",
            "folder": "thumbnail/material"
        },
        "154": {
            "name": "リンの想いの純結晶",
            "icon": "material154.png",
            "folder": "thumbnail/material"
        },
        "155": {
            "name": "レンの想いの純結晶",
            "icon": "material155.png",
            "folder": "thumbnail/material"
        },
        "156": {
            "name": "ルカの想いの純結晶",
            "icon": "material156.png",
            "folder": "thumbnail/material"
        },
        "157": {
            "name": "MEIKOの想いの純結晶",
            "icon": "material157.png",
            "folder": "thumbnail/material"
        },
        "158": {
            "name": "KAITOの想いの純結晶",
            "icon": "material158.png",
            "folder": "thumbnail/material"
        },
        "159": {
            "name": "Leo/needの想いの純結晶",
            "icon": "material159.png",
            "folder": "thumbnail/material"
        },
        "160": {
            "name": "MORE MORE JUMP！の想いの純結晶",
            "icon": "material160.png",
            "folder": "thumbnail/material"
        },
        "161": {
            "name": "Vivid BAD SQUADの想いの純結晶",
            "icon": "material161.png",
            "folder": "thumbnail/material"
        },
        "162": {
            "name": "ワンダーランズ×ショウタイムの想いの純結晶",
            "icon": "material162.png",
            "folder": "thumbnail/material"
        },
        "163": {
            "name": "25時、ナイトコードで。の想いの純結晶",
            "icon": "material163.png",
            "folder": "thumbnail/material"
        },
        "164": {
            "name": "バーチャル・シンガーの想いの純結晶",
            "icon": "material164.png",
            "folder": "thumbnail/material"
        },
        "165": {
            "name": "メモリアル★4メンバーチケット",
            "icon": "material165.png",
            "folder": "thumbnail/material"
        },
        "166": {
            "name": "ワイルドフォーチュンフラワー",
            "icon": "material166.png",
            "folder": "thumbnail/material"
        },
        "167": {
            "name": "[劇場版]★2メンバーチケット",
            "icon": "material167.png",
            "folder": "thumbnail/material"
        },
        "168": {
            "name": "七色のメモリア",
            "icon": "material168.png",
            "folder": "thumbnail/material"
        },
        "169": {
            "name": "「コネクトライブ Ensemble in SEKAI」コネクトライブver. ボーカル引き換えカード",
            "icon": "material169.png",
            "folder": "thumbnail/material"
        },
        "170": {
            "name": "ワールドピース",
            "icon": "material170.png",
            "folder": "thumbnail/material"
        },
        "171": {
            "name": "[4.5周年記念]ギフトチケット",
            "icon": "material171.png",
            "folder": "thumbnail/material"
        },
        "172": {
            "name": "「コネクトライブ Dreamscape」コネクトライブver. ボーカル引き換えカード",
            "icon": "material172.png",
            "folder": "thumbnail/material"
        },
        "173": {
            "name": "ごっちピース",
            "icon": "material173.png",
            "folder": "thumbnail/material"
        },
        "174": {
            "name": "祝祭のあまつゆ（スカイブルー）",
            "icon": "material174.png",
            "folder": "thumbnail/material"
        },
        "175": {
            "name": "祝祭のあまつゆ（パッションイエロー）",
            "icon": "material175.png",
            "folder": "thumbnail/material"
        },
        "176": {
            "name": "祝祭のあまつゆ（ポピーレッド）",
            "icon": "material176.png",
            "folder": "thumbnail/material"
        },
        "177": {
            "name": "祝祭のあまつゆ（イエローグリーン）",
            "icon": "material177.png",
            "folder": "thumbnail/material"
        },
        "178": {
            "name": "祝祭のあまつゆ（アプリコット）",
            "icon": "material178.png",
            "folder": "thumbnail/material"
        },
        "179": {
            "name": "祝祭のあまつゆ（ストリクトブルー）",
            "icon": "material179.png",
            "folder": "thumbnail/material"
        },
        "180": {
            "name": "祝祭のあまつゆ（ラブリーピンク）",
            "icon": "material180.png",
            "folder": "thumbnail/material"
        },
        "181": {
            "name": "祝祭のあまつゆ（オパールグリーン）",
            "icon": "material181.png",
            "folder": "thumbnail/material"
        },
        "182": {
            "name": "祝祭のあまつゆ（スリーズ）",
            "icon": "material182.png",
            "folder": "thumbnail/material"
        },
        "183": {
            "name": "祝祭のあまつゆ（ターコイズブルー）",
            "icon": "material183.png",
            "folder": "thumbnail/material"
        },
        "184": {
            "name": "祝祭のあまつゆ（ジョリーコーラル）",
            "icon": "material184.png",
            "folder": "thumbnail/material"
        },
        "185": {
            "name": "祝祭のあまつゆ（ロイヤルブルー）",
            "icon": "material185.png",
            "folder": "thumbnail/material"
        },
        "186": {
            "name": "祝祭のあまつゆ（サンフラワー）",
            "icon": "material186.png",
            "folder": "thumbnail/material"
        },
        "187": {
            "name": "祝祭のあまつゆ（ポカポカピンク）",
            "icon": "material187.png",
            "folder": "thumbnail/material"
        },
        "188": {
            "name": "祝祭のあまつゆ（スプリンググリーン）",
            "icon": "material188.png",
            "folder": "thumbnail/material"
        },
        "189": {
            "name": "祝祭のあまつゆ（カンパヌラパープル）",
            "icon": "material189.png",
            "folder": "thumbnail/material"
        },
        "190": {
            "name": "祝祭のあまつゆ（ファリダ）",
            "icon": "material190.png",
            "folder": "thumbnail/material"
        },
        "191": {
            "name": "祝祭のあまつゆ（ウィスタリア）",
            "icon": "material191.png",
            "folder": "thumbnail/material"
        },
        "192": {
            "name": "祝祭のあまつゆ（キャメル）",
            "icon": "material192.png",
            "folder": "thumbnail/material"
        },
        "193": {
            "name": "祝祭のあまつゆ（シッスル）",
            "icon": "material193.png",
            "folder": "thumbnail/material"
        },
        "194": {
            "name": "祝祭のあまつゆ（ブルーグリーン）",
            "icon": "material194.png",
            "folder": "thumbnail/material"
        },
        "195": {
            "name": "祝祭のあまつゆ（オレンジ）",
            "icon": "material195.png",
            "folder": "thumbnail/material"
        },
        "196": {
            "name": "祝祭のあまつゆ（イエロー）",
            "icon": "material196.png",
            "folder": "thumbnail/material"
        },
        "197": {
            "name": "祝祭のあまつゆ（ピンク）",
            "icon": "material197.png",
            "folder": "thumbnail/material"
        },
        "198": {
            "name": "祝祭のあまつゆ（レッド）",
            "icon": "material198.png",
            "folder": "thumbnail/material"
        },
        "199": {
            "name": "祝祭のあまつゆ（ブルー）",
            "icon": "material199.png",
            "folder": "thumbnail/material"
        },
        "200": {
            "name": "レッドメモリーピース",
            "icon": "material200.png",
            "folder": "thumbnail/material"
        },
        "201": {
            "name": "ブルーメモリーピース",
            "icon": "material201.png",
            "folder": "thumbnail/material"
        },
        "202": {
            "name": "パープルメモリーピース",
            "icon": "material202.png",
            "folder": "thumbnail/material"
        },
        "203": {
            "name": "レインボーメモリーピース",
            "icon": "material203.png",
            "folder": "thumbnail/material"
        },
        "204": {
            "name": "レインボーメロディ",
            "icon": "material204.png",
            "folder": "thumbnail/material"
        },
        "205": {
            "name": "夢の宝玉（白）",
            "icon": "material205.png",
            "folder": "thumbnail/material"
        },
        "206": {
            "name": "夢の宝玉（青）",
            "icon": "material206.png",
            "folder": "thumbnail/material"
        },
        "207": {
            "name": "夢の宝玉（緑）",
            "icon": "material207.png",
            "folder": "thumbnail/material"
        },
        "208": {
            "name": "夢の宝玉（赤）",
            "icon": "material208.png",
            "folder": "thumbnail/material"
        },
        "209": {
            "name": "夢の宝玉（橙）",
            "icon": "material209.png",
            "folder": "thumbnail/material"
        },
        "210": {
            "name": "夢の宝玉（紫）",
            "icon": "material210.png",
            "folder": "thumbnail/material"
        },
        "211": {
            "name": "ゴールドメダル",
            "icon": "material211.png",
            "folder": "thumbnail/material"
        },
        "213": {
            "name": "「コネクトライブ わん！もあ！HAPPY TIME」コネクトライブver. ボーカル引き換えカード",
            "icon": "material213.png",
            "folder": "thumbnail/material"
        },
        "214": {
            "name": "メモリアル★4メンバーチケット",
            "icon": "material214.png",
            "folder": "thumbnail/material"
        },
        "215": {
            "name": "メモリアルギフトチケット",
            "icon": "material215.png",
            "folder": "thumbnail/material"
        },
        "216": {
            "name": "福運の紙きれ",
            "icon": "material216.png",
            "folder": "thumbnail/material"
        },
        "217": {
            "name": "財運の紙きれ",
            "icon": "material217.png",
            "folder": "thumbnail/material"
        },
        "218": {
            "name": "福運の白札",
            "icon": "material218.png",
            "folder": "thumbnail/material"
        },
        "219": {
            "name": "福運の白札（大）",
            "icon": "material219.png",
            "folder": "thumbnail/material"
        },
        "220": {
            "name": "福運の白札（特）",
            "icon": "material220.png",
            "folder": "thumbnail/material"
        },
        "221": {
            "name": "福運の白札（極）",
            "icon": "material221.png",
            "folder": "thumbnail/material"
        },
        "222": {
            "name": "財運の白札",
            "icon": "material222.png",
            "folder": "thumbnail/material"
        },
        "223": {
            "name": "財運の白札（大）",
            "icon": "material223.png",
            "folder": "thumbnail/material"
        },
        "224": {
            "name": "財運の白札（特）",
            "icon": "material224.png",
            "folder": "thumbnail/material"
        },
        "225": {
            "name": "財運の白札（極）",
            "icon": "material225.png",
            "folder": "thumbnail/material"
        },
        "226": {
            "name": "フェイヴバルーン",
            "icon": "material226.png",
            "folder": "thumbnail/material"
        },
        "227": {
            "name": "ノーブルフェイヴバルーン（一歌）",
            "icon": "material227.png",
            "folder": "thumbnail/material"
        },
        "228": {
            "name": "ロイヤルフェイヴバルーン（一歌）",
            "icon": "material228.png",
            "folder": "thumbnail/material"
        },
        "229": {
            "name": "ノーブルフェイヴバルーン（咲希）",
            "icon": "material229.png",
            "folder": "thumbnail/material"
        },
        "230": {
            "name": "ロイヤルフェイヴバルーン（咲希）",
            "icon": "material230.png",
            "folder": "thumbnail/material"
        },
        "231": {
            "name": "ノーブルフェイヴバルーン（穂波）",
            "icon": "material231.png",
            "folder": "thumbnail/material"
        },
        "232": {
            "name": "ロイヤルフェイヴバルーン（穂波）",
            "icon": "material232.png",
            "folder": "thumbnail/material"
        },
        "233": {
            "name": "ノーブルフェイヴバルーン（志歩）",
            "icon": "material233.png",
            "folder": "thumbnail/material"
        },
        "234": {
            "name": "ロイヤルフェイヴバルーン（志歩）",
            "icon": "material234.png",
            "folder": "thumbnail/material"
        },
        "235": {
            "name": "ノーブルフェイヴバルーン（みのり）",
            "icon": "material235.png",
            "folder": "thumbnail/material"
        },
        "236": {
            "name": "ロイヤルフェイヴバルーン（みのり）",
            "icon": "material236.png",
            "folder": "thumbnail/material"
        },
        "237": {
            "name": "ノーブルフェイヴバルーン（遥）",
            "icon": "material237.png",
            "folder": "thumbnail/material"
        },
        "238": {
            "name": "ロイヤルフェイヴバルーン（遥）",
            "icon": "material238.png",
            "folder": "thumbnail/material"
        },
        "239": {
            "name": "ノーブルフェイヴバルーン（愛莉）",
            "icon": "material239.png",
            "folder": "thumbnail/material"
        },
        "240": {
            "name": "ロイヤルフェイヴバルーン（愛莉）",
            "icon": "material240.png",
            "folder": "thumbnail/material"
        },
        "241": {
            "name": "ノーブルフェイヴバルーン（雫）",
            "icon": "material241.png",
            "folder": "thumbnail/material"
        },
        "242": {
            "name": "ロイヤルフェイヴバルーン（雫）",
            "icon": "material242.png",
            "folder": "thumbnail/material"
        },
        "243": {
            "name": "ノーブルフェイヴバルーン（こはね）",
            "icon": "material243.png",
            "folder": "thumbnail/material"
        },
        "244": {
            "name": "ロイヤルフェイヴバルーン（こはね）",
            "icon": "material244.png",
            "folder": "thumbnail/material"
        },
        "245": {
            "name": "ノーブルフェイヴバルーン（杏）",
            "icon": "material245.png",
            "folder": "thumbnail/material"
        },
        "246": {
            "name": "ロイヤルフェイヴバルーン（杏）",
            "icon": "material246.png",
            "folder": "thumbnail/material"
        },
        "247": {
            "name": "ノーブルフェイヴバルーン（彰人）",
            "icon": "material247.png",
            "folder": "thumbnail/material"
        },
        "248": {
            "name": "ロイヤルフェイヴバルーン（彰人）",
            "icon": "material248.png",
            "folder": "thumbnail/material"
        },
        "249": {
            "name": "ノーブルフェイヴバルーン（冬弥）",
            "icon": "material249.png",
            "folder": "thumbnail/material"
        },
        "250": {
            "name": "ロイヤルフェイヴバルーン（冬弥）",
            "icon": "material250.png",
            "folder": "thumbnail/material"
        },
        "251": {
            "name": "ノーブルフェイヴバルーン（司）",
            "icon": "material251.png",
            "folder": "thumbnail/material"
        },
        "252": {
            "name": "ロイヤルフェイヴバルーン（司）",
            "icon": "material252.png",
            "folder": "thumbnail/material"
        },
        "253": {
            "name": "ノーブルフェイヴバルーン（えむ）",
            "icon": "material253.png",
            "folder": "thumbnail/material"
        },
        "254": {
            "name": "ロイヤルフェイヴバルーン（えむ）",
            "icon": "material254.png",
            "folder": "thumbnail/material"
        },
        "255": {
            "name": "ノーブルフェイヴバルーン（寧々）",
            "icon": "material255.png",
            "folder": "thumbnail/material"
        },
        "256": {
            "name": "ロイヤルフェイヴバルーン（寧々）",
            "icon": "material256.png",
            "folder": "thumbnail/material"
        },
        "257": {
            "name": "ノーブルフェイヴバルーン（類）",
            "icon": "material257.png",
            "folder": "thumbnail/material"
        },
        "258": {
            "name": "ロイヤルフェイヴバルーン（類）",
            "icon": "material258.png",
            "folder": "thumbnail/material"
        },
        "259": {
            "name": "ノーブルフェイヴバルーン（奏）",
            "icon": "material259.png",
            "folder": "thumbnail/material"
        },
        "260": {
            "name": "ロイヤルフェイヴバルーン（奏）",
            "icon": "material260.png",
            "folder": "thumbnail/material"
        },
        "261": {
            "name": "ノーブルフェイヴバルーン（まふゆ）",
            "icon": "material261.png",
            "folder": "thumbnail/material"
        },
        "262": {
            "name": "ロイヤルフェイヴバルーン（まふゆ）",
            "icon": "material262.png",
            "folder": "thumbnail/material"
        },
        "263": {
            "name": "ノーブルフェイヴバルーン（絵名）",
            "icon": "material263.png",
            "folder": "thumbnail/material"
        },
        "264": {
            "name": "ロイヤルフェイヴバルーン（絵名）",
            "icon": "material264.png",
            "folder": "thumbnail/material"
        },
        "265": {
            "name": "ノーブルフェイヴバルーン（瑞希）",
            "icon": "material265.png",
            "folder": "thumbnail/material"
        },
        "266": {
            "name": "ロイヤルフェイヴバルーン（瑞希）",
            "icon": "material266.png",
            "folder": "thumbnail/material"
        },
        "267": {
            "name": "ノーブルフェイヴバルーン（ミク）",
            "icon": "material267.png",
            "folder": "thumbnail/material"
        },
        "268": {
            "name": "ロイヤルフェイヴバルーン（ミク）",
            "icon": "material268.png",
            "folder": "thumbnail/material"
        },
        "269": {
            "name": "ノーブルフェイヴバルーン（リン）",
            "icon": "material269.png",
            "folder": "thumbnail/material"
        },
        "270": {
            "name": "ロイヤルフェイヴバルーン（リン）",
            "icon": "material270.png",
            "folder": "thumbnail/material"
        },
        "271": {
            "name": "ノーブルフェイヴバルーン（レン）",
            "icon": "material271.png",
            "folder": "thumbnail/material"
        },
        "272": {
            "name": "ロイヤルフェイヴバルーン（レン）",
            "icon": "material272.png",
            "folder": "thumbnail/material"
        },
        "273": {
            "name": "ノーブルフェイヴバルーン（ルカ）",
            "icon": "material273.png",
            "folder": "thumbnail/material"
        },
        "274": {
            "name": "ロイヤルフェイヴバルーン（ルカ）",
            "icon": "material274.png",
            "folder": "thumbnail/material"
        },
        "275": {
            "name": "ノーブルフェイヴバルーン（MEIKO）",
            "icon": "material275.png",
            "folder": "thumbnail/material"
        },
        "276": {
            "name": "ロイヤルフェイヴバルーン（MEIKO）",
            "icon": "material276.png",
            "folder": "thumbnail/material"
        },
        "277": {
            "name": "ノーブルフェイヴバルーン（KAITO）",
            "icon": "material277.png",
            "folder": "thumbnail/material"
        },
        "278": {
            "name": "ロイヤルフェイヴバルーン（KAITO）",
            "icon": "material278.png",
            "folder": "thumbnail/material"
        },
        "279": {
            "name": "インタビューご協力のお願い\n（※2月実施アンケートで協力可と回答された一部の方へ送信しています）",
            "icon": "material279.png",
            "folder": "thumbnail/material"
        },
        "280": {
            "name": "「コネクトライブ Parallel Paaaarty!!!!」コネクトライブver. ボーカル引き換えカード",
            "icon": "material280.png",
            "folder": "thumbnail/material"
        },
        "281": {
            "name": "プラチナチケット",
            "icon": "material281.png",
            "folder": "thumbnail/material"
        },
        "282": {
            "name": "バーチャルエールコイン",
            "icon": "material282.png",
            "folder": "thumbnail/material"
        },
        "283": {
            "name": "旋律のスフィア",
            "icon": "material283.png",
            "folder": "thumbnail/material"
        },
        "284": {
            "name": "軌跡のプリズム",
            "icon": "material284.png",
            "folder": "thumbnail/material"
        },
        "285": {
            "name": "邂逅のメモリア",
            "icon": "material285.png",
            "folder": "thumbnail/material"
        },
        "297": {
            "name": "祝祭のあまつゆ（ストリクトブルー） '26",
            "icon": "material297.png",
            "folder": "thumbnail/material"
        },
        "318": {
            "name": "メモリアルフラグメント",
            "icon": "material318.png",
            "folder": "thumbnail/material"
        },
        "319": {
            "name": "友達招待ギフトチケット",
            "icon": "material319.png",
            "folder": "thumbnail/material"
        },
        "320": {
            "name": "メモリアル★4メンバーチケット",
            "icon": "material320.png",
            "folder": "thumbnail/material"
        }
    }
};

export const HARVEST_FIXTURE_TYPES = {
    "111": "treasure_box_transport",
    "112": "treasure_box_fixed",
    "1001": "wood",
    "1002": "wood",
    "1003": "wood",
    "1004": "wood",
    "2001": "mineral",
    "2002": "mineral",
    "2003": "mineral",
    "2004": "mineral",
    "2005": "mineral",
    "2006": "mineral",
    "3001": "toolbox",
    "4001": "plant",
    "4002": "plant",
    "4003": "plant",
    "4004": "plant",
    "4005": "plant",
    "4006": "plant",
    "4007": "plant",
    "4008": "plant",
    "4009": "plant",
    "4010": "plant",
    "4011": "plant",
    "4012": "plant",
    "4013": "plant",
    "4014": "plant",
    "4015": "plant",
    "4016": "plant",
    "4017": "plant",
    "5001": "other",
    "5002": "other",
    "5003": "other",
    "5004": "other",
    "5101": "other",
    "5102": "other",
    "5103": "other",
    "5104": "other",
    "6001": "driftage",
    "7001": "tone",
    "8001": "birthday_plant",
    "8002": "birthday_plant",
    "8003": "birthday_plant",
    "8004": "birthday_plant",
    "8005": "birthday_plant",
    "8006": "birthday_plant",
    "8007": "birthday_plant",
    "8008": "birthday_plant",
    "8009": "birthday_plant",
    "8010": "birthday_plant",
    "8011": "birthday_plant",
    "8012": "birthday_plant",
    "8013": "birthday_plant",
    "8014": "birthday_plant",
    "8015": "birthday_plant",
    "8016": "birthday_plant",
    "8017": "birthday_plant",
    "8018": "birthday_plant",
    "8019": "birthday_plant",
    "8020": "birthday_plant",
    "8021": "birthday_plant",
    "8022": "birthday_plant",
    "8023": "birthday_plant",
    "8024": "birthday_plant",
    "8025": "birthday_plant",
    "8026": "birthday_plant",
    "8027": "birthday_plant"
};
